version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "wsi-back"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-0fb4aafa15c48982d"
              - "subnet-0c179fd9595fc4862"
            SecurityGroups:
              - "sg-0a8fda669807fdaa2"
            AssignPublicIp: "DISABLED"
