version: 0.2
run-as: root

env:
  variables:
    REPO: "060764678458.dkr.ecr.ap-northeast-1.amazonaws.com/wsi-image-repo"
    REGION: "ap-northeast-1"

phases:
  pre_build: 
    commands:
      - echo Logging in to AWS ECR
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 060764678458.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build Process Start...
      - echo Building the Docker image...
      - docker build -t $REPO:backend-application .
  post_build:
    commands:
      - echo Pushing Container Image to AWS ECR...
      - docker push $REPO:backend-application

artifacts:
  files:
    - "config/appspec.yaml"
    - "config/taskdef.json"
