apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cloudskills-back-front-deployment-hpa
  namespace: wsi-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudskills-front-app-deployment
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50
